<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Recommendation extends \App\Entity\Recommendation implements \Doctrine\Persistence\Proxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
        __clone as private __doClone;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".'*'."\0".'modifiedAt' => [parent::class, 'modifiedAt', null],
        "\0".parent::class."\0".'createdBy' => [parent::class, 'createdBy', null],
        "\0".parent::class."\0".'descriptionCare' => [parent::class, 'descriptionCare', null],
        "\0".parent::class."\0".'humidityRange' => [parent::class, 'humidityRange', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'illuminationRange' => [parent::class, 'illuminationRange', null],
        "\0".parent::class."\0".'modifiedBy' => [parent::class, 'modifiedBy', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'temperatureRange' => [parent::class, 'temperatureRange', null],
        "\0".parent::class."\0".'types' => [parent::class, 'types', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'createdBy' => [parent::class, 'createdBy', null],
        'descriptionCare' => [parent::class, 'descriptionCare', null],
        'humidityRange' => [parent::class, 'humidityRange', null],
        'id' => [parent::class, 'id', null],
        'illuminationRange' => [parent::class, 'illuminationRange', null],
        'modifiedAt' => [parent::class, 'modifiedAt', null],
        'modifiedBy' => [parent::class, 'modifiedBy', null],
        'name' => [parent::class, 'name', null],
        'temperatureRange' => [parent::class, 'temperatureRange', null],
        'types' => [parent::class, 'types', null],
    ];

    /**
     * @internal
     */
    public bool $__isCloning = false;

    public function __construct(?\Closure $initializer = null)
    {
        self::createLazyGhost($initializer, [
            "\0".parent::class."\0".'id' => true,
            '__isCloning' => true,
        ], $this);
    }

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __clone()
    {
        $this->__isCloning = true;

        try {
            $this->__doClone();
        } finally {
            $this->__isCloning = false;
        }
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"], $properties['__isCloning']);

        return $properties;
    }
}
